### ISSUE TITLE
Error Launching Priompt Example

### ISSUE THREAD

**Issue by daniel442li** [anysphere/priompt#10]
On a clean install on MacOS, I get this error when running **pnpm watch** in /examples

`node:internal/modules/cjs/loader:444
      const err = new Error(
                  ^

Error: Cannot find module '/Users/daniel-li/Code/priompt/examples/node_modules/@anysphere/priompt/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:444:19)
    at Module._findPath (node:internal/modules/cjs/loader:714:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:27)
    at l.default._resolveFilename (/Users/daniel-li/Code/priompt/node_modules/.pnpm/tsx@3.14.0/node_modules/tsx/dist/cjs/index.cjs:1:1671)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at error (/Users/daniel-li/Code/priompt/examples/src/index.ts:1:89)
    at Object.<anonymous> (/Users/daniel-li/Code/priompt/examples/src/index.ts:204:11)
    at Module._compile (node:internal/modules/cjs/loader:1375:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/daniel-li/Code/priompt/examples/node_modules/@anysphere/priompt/package.json',
  requestPath: '@anysphere/priompt'
}

Node.js v21.5.0`

Seems like I'm doing something wrong with my dev dependencies. Any ideas? Thanks!

**Comment by pavelsvitek** [comment]
Try building it first with `npm build` / `yarn build` / `pnpm build`
