### ISSUE TITLE
"statusCode":500

### ISSUE THREAD

**Issue by ECEAthipanbose** [anysphere/priompt#19]
curl 'localhost:8008/message?message=what%20is%20the%20advantage%20of%20rust%20over%20c&name=a%20curious%20explorer'

i got error like this 
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of undefined (reading 'numTokens')"}(base)

**Comment by johnstew** [comment]
FWIW, I'm getting the same thing locally as well. It looks like the error is coming from within the library itself. 

```
TypeError: Cannot read properties of undefined (reading 'numTokens')
    at numTokensPromptString (/Users/John/Dev/priompt/priompt/dist/lib.js:2452:22)
    at countMsgTokens (/Users/John/Dev/priompt/priompt/dist/lib.js:2817:31)
    at /Users/John/Dev/priompt/priompt/dist/lib.js:2513:72
    at Array.map (<anonymous>)
    at countTokensExact (/Users/John/Dev/priompt/priompt/dist/lib.js:2513:61)
    at renderBinarySearch (/Users/John/Dev/priompt/priompt/dist/lib.js:831:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at render (/Users/John/Dev/priompt/priompt/dist/lib.js:478:12)
    at renderun (/Users/John/Dev/priompt/priompt/dist/lib.js:534:20)
    at Object.<anonymous> (/Users/John/Dev/priompt/examples/src/index.ts:125:19)
```

I'm trying to dig into this more but will have to come back.

**Comment by steventsao** [comment]
Looks like the function signature has changed for `render`. I've shared a PR to update that one instance in the example directory.
